name: Build and Create Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-image -f tools/Dockerfile ./tools

    - name: Run compile script in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/software:/src \
          my-image \
          /bin/sh -c "cd /src/main_emmg && ./compile.sh"

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::release-$(date +'%Y.%m.%d-%H%M%S')"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: Release ${{ steps.tag.outputs.release_tag }}
        draft: false
        prerelease: false
        files: ./software/main_emmg/build/main_emmg.ino.uf2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
